version: '3.8'

services:
  drone-postgres:
    image: postgres:15-alpine
    container_name: drone-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alphaflight7
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  telemetry-api:
    build: ./backend
    container_name: telemetry-api
    dns:
      - 8.8.8.8
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - PYTHONUNBUFFERED=1
    depends_on:
      - drone-postgres
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: telemetry_queue
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: on-failure

  telemetry-worker:
    build: ./backend
    container_name: telemetry_worker
    command: sh -c "sleep 10 && python -u worker.py"
    dns:
      - 8.8.8.8
    volumes:
      - ./backend:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DATABASE_URL=postgresql://postgres:alphaflight7@drone-postgres:5432/postgres
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - drone-postgres
    restart: always
    
  drone-simulator:
    build: ./simulator
    container_name: drone-simulator
    depends_on:
      - telemetry-api
    restart: always

volumes:
  postgres_data: